export const abi1 = [
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "propId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
      ],
      name: "PriceChanged",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "propId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "PropertyOwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "uint256",
          name: "propId",
          type: "uint256",
        },
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: false,
          internalType: "string",
          name: "location",
          type: "string",
        },
        { indexed: false, internalType: "string", name: "area", type: "string" },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
      ],
      name: "PropertyRegistered",
      type: "event",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        { internalType: "uint256", name: "propertyId", type: "uint256" },
        { internalType: "uint256", name: "price", type: "uint256" },
      ],
      name: "changePrice",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "propertyId", type: "uint256" }],
      name: "getLastTransfer",
      outputs: [
        {
          components: [
            { internalType: "address", name: "previousOwner", type: "address" },
            { internalType: "address", name: "newOwner", type: "address" },
            { internalType: "uint256", name: "transferTime", type: "uint256" },
          ],
          internalType: "struct PropertyRegistry.LastTransfer",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "propertyId", type: "uint256" }],
      name: "getPropertyDetails",
      outputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "listAllProperties",
      outputs: [
        {
          components: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "uint256", name: "propId", type: "uint256" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "category", type: "string" },
            { internalType: "string", name: "location", type: "string" },
            { internalType: "string", name: "area", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "string", name: "image", type: "string" },
            { internalType: "uint256", name: "price", type: "uint256" },
          ],
          internalType: "struct PropertyRegistry.Property[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "owner", type: "address" }],
      name: "listPropertiesByOwner",
      outputs: [
        {
          components: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "uint256", name: "propId", type: "uint256" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "category", type: "string" },
            { internalType: "string", name: "location", type: "string" },
            { internalType: "string", name: "area", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "string", name: "image", type: "string" },
            { internalType: "uint256", name: "price", type: "uint256" },
          ],
          internalType: "struct PropertyRegistry.Property[]",
          name: "",
          type: "tuple[]",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        { internalType: "uint256", name: "propertyId", type: "uint256" },
        { internalType: "string", name: "_propName", type: "string" },
        { internalType: "string", name: "_category", type: "string" },
        { internalType: "string", name: "_location", type: "string" },
        { internalType: "string", name: "_description", type: "string" },
        { internalType: "string", name: "_image", type: "string" },
      ],
      name: "modifyDetails",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "numberOfProperties",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "purchaser", type: "address" },
        { internalType: "uint256", name: "propertyId", type: "uint256" },
      ],
      name: "purchaseProperty",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        { internalType: "string", name: "_propName", type: "string" },
        { internalType: "string", name: "_category", type: "string" },
        { internalType: "string", name: "_location", type: "string" },
        { internalType: "string", name: "_area", type: "string" },
        { internalType: "string", name: "_description", type: "string" },
        { internalType: "string", name: "_image", type: "string" },
        { internalType: "uint256", name: "price", type: "uint256" },
      ],
      name: "registerProperty",
      outputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
      ],
      stateMutability: "nonpayable",
      type: "function",
    },
  ];
  